confluence_data_freshness/confluence_data_freshness/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cdr/', include('confluence_data_retriever.urls')),
]

confluence_data_freshness/confluence_data_retriever/urls.py
from django.urls import path

from . import views

app_name = "confluence_data_retriever"
urlpatterns = [
    path('children/<int:hub_page_id>', views.children, name='children'),
    path('searching', views.search, name='search_action'),
    path('search', views.SearchView.as_view(), name='search'),
    path('get_csv', views.get_csv, name='get_csv'),
    
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
]

confluence_data_freshness/confluence_data_retriever/models.py
from django.db import models

# Create your models here.

confluence_data_freshness/confluence_data_retriever/views.py
from bdb import Breakpoint
import re

from django.views import generic
from django.shortcuts import redirect, render
from django.http import HttpResponse
import pandas as pd
import json
from .confluence.extractor import Extractor
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

def children(request, hub_page_id):
    template_name = 'confluence_data_retriever/children.html'

    extractor = Extractor()
    extractor.append_hub_page(hub_page_id, 0)
    extractor.append_children_pages(hub_page_id, 1)

    all_pages = extractor.get_all_pages()

    return render(request, template_name, {'all_pages': all_pages})
        

class SearchView(generic.TemplateView):
    template_name = 'confluence_data_retriever/search.html'


def search(request):
    hub_page_url = request.POST['hub_page_url'] 
    search_string = re.search('\d{1,60}', hub_page_url, re.IGNORECASE)

    if search_string:
        hub_page_id = search_string.group(0)
    
    return redirect(f'children/{hub_page_id}')

@method_decorator(csrf_exempt, name='dispatch')
def get_csv(request):
    body_unicode = request.body.decode('utf-8')
    x = body_unicode.replace("'", '"')
    body = json.loads(x)
    

    output_df = pd.DataFrame(body)
    
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=export.csv'
    output_df.to_csv(path_or_buf=response, sep=',', encoding='utf-8')
    
    return response

confluence_data_freshness/confluence_data_retriever/templates/confluence_data_retriever/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>



    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/google_template.css' %}" />


</head>

<body>
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

confluence_data_freshness/confluence_data_retriever/templates/confluence_data_retriever/children.html
{% extends 'confluence_data_retriever/base.html' %}
{% block title %}Freshness Report{% endblock %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
        crossorigin="anonymous">
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script>
function download(){
    var yourArray = []
    $("input:checkbox[name=item_table]:checked").each(function(){
        yourArray.push($(this).val());
    });
    if(yourArray.length === 0){
        $("input:checkbox[name=item_table]").each(function(){
            yourArray.push($(this).val());
        });
    }
    console.log(yourArray)
    const options = {
        method: 'POST',
        headers: {'Content-Type': 'application/json', 'X-CSRFToken': 'aaaaaa'},
        body: `[${yourArray}]`
    }
      
      fetch('http://127.0.0.1:8000/cdr/get_csv', options)
        .then((res) => res.blob())
        .then((blob) => URL.createObjectURL(blob))
        .then((href) => {
            Object.assign(document.createElement('a'), {
            href,
            download: 'confluence_pages.csv',
            }).click()})
        .catch(err => console.error(err));
    
}
</script>
{% csrf_token %}
<button class="btn" style="width:10%" onclick="download()"><i class="fa fa-download"></i> Download CSV</button>
<table class="styled-table">
    <thead>
        <tr>
            <th><input type=checkbox
                onclick="[...closest('table').querySelectorAll('tbody [type=checkbox]')].forEach(box=>box.checked=checked)">
            </th>
            <th>#ID</th>
            <th>Level</th>
            <th>Page</th>
            <th>Creation User</th>
            <th>Last Update User</th>
            <th>Days since Last Update</th>
            <th>Days since Creation</th>
            <th>Creation Date</th>
            <th>Last Update Date</th>
            <th>Labels</th>
        </tr>
    </thead>
    <tbody>
        {% for page in all_pages %}
        <tr bgcolor="{{ page.color }}">
            <td><input type="checkbox" name="item_table" value="{{page}}"/></td>
            <td><a target="_blank" href="{{ page.page_link }}">{{ page.id }}</a></td>
            <td>{{ page.page_level }}</td>
            <td>{{ page.page_title }}</td>
            <td>{{ page.create_user }}</td>
            <td>{{ page.last_updated_user }}</td>
            <td>{{ page.days_from_last_update }}</td>
            <td>{{ page.days_from_creation }}</td>
            <td>{{ page.create_date }}</td>
            <td>{{ page.last_updated_date }}</td>
            <td>
                {% for label in page.labels %}
                    <div class="chip">
                        {{ label }}
                    </div>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

confluence_data_freshness/confluence_data_retriever/templates/confluence_data_retriever/search.html
{% extends 'confluence_data_retriever/base.html' %}
{% load static %}
{% block title %}Search Page{% endblock %}
{% block content %}
<form action="{% url 'confluence_data_retriever:search_action' %}" method="post">
  {% csrf_token %}
  <section>
    <div class="container">
      <img id="logo" width="200px" src="{% static 'assets/logo.png' %}" />
      <div class="search">
        <input id="hub_page_url" type="text" name="hub_page_url">
      </div>
      <div class="search_btn">
        <input class="button" type="submit" name="submit" value="Submit" />
      </div>
    </div>
  </section>
</form>
{% endblock %}